config/routes.rb
Rails.application.routes.draw do
  get 'farm/index'

  get 'farm/:unique_key', to: 'farm#edit', as: 'edit_farm'
  patch 'farm/update'

  get 'order/index'
  get 'order/show'
  get 'order/list'
  get 'order/details/:id', to: 'order#details', as: 'order_details'
  get 'order/farm_order_availability'
  post 'order/create'
  patch 'order/filled'
  patch 'order/delivered'
  patch 'order/cancel_order/:id', to: 'order#cancel_order', as: 'cancel_order'

  root to: 'order#index'
  # mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farm.rb
class Farm < ApplicationRecord
  has_many :orders

  validates :unique_key, presence: true

  def available_eggs_count
    pending_orders = orders.where(filled: false)
    available_eggs = total_eggs - pending_orders.sum(&:qty)
    available_eggs > 0 ? total_eggs : 0
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :farm
  validates :qty, numericality: true
  validates :qty, presence: true

  enum payment: { '0': 'Cash', '1': 'Check' }

  def status
    if filled && delivered
      'Filled & Delivered'
    elsif filled && !delivered
      'Filled, not Delivered'
    else
      'Not Processed Yet'
    end
  end

  def pickup_location
    PickupLocation.find(pickup_location_id).name unless pickup_location_id.nil?
  end

  def cost
    total = qty * 3
    total += 2 if Order.payments[payment_type.to_s] == 'Delivered'
    total
  end

  def estimate_delivery_date
    pending_qty = farm.orders.where(filled: false).where.not(id: id).sum(&:qty)
    calculated_egg_count = farm.total_eggs - pending_qty - qty
    if calculated_egg_count.positive? || calculated_egg_count.zero?
      # mark estimated due date as today
      Date.today
    else
      # take calcaulted egg count
      Date.today + calculated_egg_count.abs.days
    end
  end
end

app/models/pickup_location.rb
class PickupLocation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  validates :phone_number, presence: true
  validates :phone_number, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/farm_controller.rb
class FarmController < ApplicationController
  def index; end

  def edit
    @farm = Farm.find_by(unique_key: params[:unique_key])
  end

  def update
    @farm = Farm.find(params[:id])

    if @farm.update(farm_params)
      flash[:notice] = 'Farm information updated.'
    else
      flash[:alert] = "There was an error when updating farm: #{@farm.errors.messages}"
    end
    redirect_to edit_farm_path(@farm.unique_key)
  end

  private

  def farm_params
    params.require(:farm).permit(:name, :address, :city, :state, :zipcode, :total_eggs,
                                 :phone_number, :egg_cost, :chicken_count)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  protect_from_forgery except: %i[filled delivered]

  def index
    @farms = Farm.all
    @pickup_locations = PickupLocation.all
    @farm = Farm.first
  end

  def create
    user = User.find_by(phone_number: params[:order][:phone_number])

    @user = user.nil? ? User.new(user_params) : user
    @user.email = params[:order][:email] unless params[:order][:email].blank?
    @order = @user.orders.build(order_params)

    ActiveRecord::Base.transaction do
      begin
        @user.save!
        @order.save!
        OrderMailer.with(order: @order, user: @user).new_order.deliver_now
        flash[:notice] = 'Your order has been placed. You will hear from us soon.'
        redirect_to order_details_path(@order.id)
      rescue ActiveRecord::RecordInvalid => invalid
        return_message = ''
        invalid.record.errors.messages.each do |message|
          return_message << message[0].to_s + ' ' + message[1].join(',') + '\n'
        end
        flash[:alert] = return_message
        redirect_to order_index_path
      end
    end
  end

  def show
    @orders = Order.all.sort
  end

  def filled
    order = Order.find(params[:id])
    ActiveRecord::Base.transaction do
      OrderMailer.with(order: order, user: order.user).order_filled.deliver_now if !order.user.email.blank?
      order.update(filled: params[:checked])
      order.farm.update(total_eggs: order.farm.total_eggs - order.qty)
    end
  end

  def delivered
    order = Order.find(params[:id])
    order.update(delivered: params[:checked])
  end

  def list
    user = User.find_by(phone_number: params[:past_orders][:phone_number])
    @orders = user.nil? ? [] : user.orders
  end

  def details
    @order = Order.find(params[:id])
    @payment_type = Order.payments[@order.payment_type.to_s]
  end

  def farm_order_availability
    @farm = Farm.find(params[:id])

    render json: { farm: @farm, available_eggs: @farm.available_eggs_count, egg_cost: @farm.egg_cost }
  end

  def cancel_order
    @order = Order.find(params[:id])
    @order.update!(cancelled: true)
    flash[:notice] = 'Your order has been cancelled.'
  rescue ActiveRecord::RecordInvalid => invalid
    flash[:alert] = invalid.record.errors.messages
  ensure
    redirect_to order_list_path(past_orders: { phone_number: @order.user.phone_number })
  end

  private

  def user_params
    params.require(:order).permit(:first_name, :last_name, :phone_number, :email)
  end

  def order_params
    params.require(:order).permit(:qty, :pickup_location_id, :farm_id, :payment_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farm_helper.rb
module FarmHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/farm/edit.html.erb
<div class="text-center" style="margin-bottom:20px;">
	<%= image_tag "cover_photo.png", width: '100%' %>
</div>

<%= form_for @farm, url: farm_update_path(id: @farm.id) do |f| %>
	<div class="row">
		<div class="form-group col-md-4 col-sm-4 col-12">
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>
		<div class="form-group col-md-4 col-sm-4 col-12">
			<%= f.label :phone_number %>
			<%= f.text_field :phone_number, class: 'form-control' %>
		</div>
		<div class="form-group col-md-4 col-sm-4, col-12">
			<%= f.label :unique_key %>
			<%= f.text_field :unique_key, class: 'form-control', disabled: true %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-12 col-sm-12 col-12">
			<%= f.label :address %>
			<%= f.text_field :address, class: 'form-control' %>
		</div>
		<div class="form-group col-md-4 col-12">
			<%= f.label :city %>
			<%= f.text_field :city, class: 'form-control' %>
		</div>
		<div class="form-group col-md-4 col-12">
			<%= f.label :state %>
			<%= f.text_field :state, class: 'form-control' %>
		</div>
		<div class="form-group col-md-4 col-12">
			<%= f.label :zipcode %>
			<%= f.text_field :zipcode, class: 'form-control' %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-4 col-sm-4, col-12">
			<%= f.label :total_eggs, "Total Eggs By Dozen" %>
			<%= f.text_field :total_eggs, class: 'form-control' %>
		</div>
		<div class="form-group col-md-4 col-sm-4, col-12">
			<%= f.label :egg_cost, "Cost Per Dozen:" %>
			<%= f.text_field :egg_cost, class: 'form-control' %>
		</div>
		<div class="form-group col-md-4 col-sm-4, col-12">
			<%= f.label :chicken_count, "How many laying hens do you have?" %>
			<%= f.text_field :chicken_count, class: 'form-control' %>
		</div>
	</div>
	<%= f.submit "Update Farm", class: 'btn btn-primary' %>
<% end %>

app/views/farm/index.html.erb
<h1>Farm#index</h1>
<p>Find me in app/views/farm/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chicken Order</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container-fluid">
      <%= render "shared/alert" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/order/details.html.erb
<%= link_to "<< Home", order_index_path %>

<%= render 'shared/order_details' %>

app/views/order/index.html.erb
<div class="jumbotron">
	<h1 class="display-4">Enter A New Order</h1>
	<%= form_for :order, url: order_create_path, method: :post do |f| %>
		<div class="row">
			<div class="form-group col-sm-4 col-12">
				<%= f.label :farm_id, "* Where are you ordering from? "%>
				<%= f.select :farm_id, @farms.collect {|p| [ p.name, p.id ]}, {:prompt => 'Select Farm Ordering From'}, {class: "form-control"} %>
				<div id='farm_order_availability' class="text-muted">
				</div>
			</div>
			<div class="form-group col-sm-4 col-12">
				<%= f.label :pickup_location_id, "* Where do you want to pickup? "%>
				<%= f.select :pickup_location_id, @pickup_locations.collect {|p| [ p.name, p.id ]}, {:prompt => 'Select Location for Pickup'}, {class: "form-control"} %>
				<div id="disclaimer" class="text-muted"></div>
			</div>
			<div class="form-group col-sm-4 col-12">
				<%= f.label :payment_type, "* Select Payment Type "%>
				<%= f.select :payment_type, Order.payments.collect {|key, value| [ value, key ]}, {}, {class: "form-control"} %>
				<div id="disclaimer" class="text-muted"></div>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-6 col-12">
				<%= f.label :first_name, "First Name: " %>
				<%= f.text_field :first_name, class: "form-control" %>
			</div>
			<div class="form-group col-sm-6 col-12">
				<%= f.label :last_name, "Last Name:" %>
				<%= f.text_field :last_name, class: "form-control" %>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-4 col-12">
				<%= f.label :phone_number, "* Phone Number:" %>
				<%= f.telephone_field :phone_number, class: "form-control" %>
			</div>
			<div class="form-group col-sm-4 col-12">
				<%= f.label :email, "Email:" %>
				<%= f.telephone_field :email, class: "form-control" %>
				<div id="email-text" class="text-muted">Only needed if you'd like email updates on your order via email.</div>
			</div>
			<div class="form-group col-sm-4 col-12">
				<%= f.label :qty, "* How Many Dozen?" %>
				<%= f.number_field :qty, class: "form-control" %>
			</div>
		</div>

		<%= f.submit "Place Order", class: "btn btn-primary"  %>
	<% end %>
</div>

<div class="jumbotron">
	<h1 class="display-4 text-center">View Order History/Status</h1>
	<%= form_for :past_orders, url: order_list_path, method: :get do |f| %>
		<div class="row">
			<div class="form-group col-sm-12 col-12 text-center">
				<%= f.label :phone_number, "Enter Phone Number to view previous orders: " %>
				<%= f.text_field :phone_number, class: "form-control col-sm-12 col-12", placeholder: "Phone Number" %>
			</div>
		</div>
		<%= f.submit "Find Orders", class: "btn btn-primary" %>
	<% end %>
</div>

<script>
	$('#order_pickup_location_id').change(function(){
		if ($(this).children('option:selected').text() === "Delivered") {
			$('#disclaimer').append("* There is a $2 delivery fee on all orders delivered to a local address. Will only deliver to a house in a 10 mile radius of the farm. We will contact you for address.")
		} else {
			$('#disclaimer').empty();
		}
	});

  $('#order_farm_id').change(function(){
  	$('#farm_order_availability').text('');
		$.ajax({
		  type: 'GET',
		  url: '/order/farm_order_availability',
		  data: {id: $(this).val()},
		  dataType: 'json',
		  success: function(data){
		  	console.log(data);
		  	$('#farm_order_availability').text(
		  		data.farm['name'] + ' currently has ' + data['available_eggs'] + ' dozen available for purchase. Cost per dozen: $' + data['egg_cost'] + ' * You can order more then is avaialble. We will fill it first come first serve.'
		  	);
		  }
		})
	});
</script>

app/views/order/list.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Order Number</th>
			<th>Name</th>
			<th>Phone Number</th>
			<th class="text-center">Order Qty (Dozen)</th>
			<th class="text-center">Total Cost</th>
			<th>Status</th>
			<th></th>
	</thead>
	<tbody>
		<% @orders.each do |order| %>
			<tr class=<%= "bg-danger" if order.cancelled %>>
				<th><%= order.id %></th>
				<td><%= order.user.first_name %> <%= order.user.last_name %></td>
				<td><%= order.user.phone_number %></td>
				<td class="text-center"><%= order.qty %></td>
				<td class="text-center">$<%= order.cost %></td>
				<td><%= order.status %></td>
				<td>
					<%= link_to "View", order_details_path(order.id) %>
					<% unless order.delivered || order.cancelled %>
						| <%= link_to "Cancel", cancel_order_path(order.id), method: :patch, data: { confirm: 'Are you sure you want to cancel this order?' } %>
					<% end %>
				</td>
			</tr>
		<% end %>
		<tr class="table-success">
			<td colspan="3" class="text-right">Total:</td>
			<td class="text-center"><%= @orders.sum(&:qty) %></td>
			<td class="text-center">$<%= @orders.sum(&:cost) %></td>
			<td/>
			<td/>
		</tr>
	</tbody>
</table>

app/views/order/show.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Order Number</th>
			<th>Name</th>
			<th>Phone Number</th>
			<th class="text-center">Order Qty (Dozen)</th>
			<th>Pickup Location</th>
			<th>Payment Type</th>
			<th class="text-center">Cost</th>
			<th>Filled?</th>
			<th>Delivered?</th>
	</thead>
	<tbody>
		<% @orders.each do |order| %>
			<tr>
				<th><%= order.id %></th>
				<td><%= order.user.first_name %> <%= order.user.last_name %></td>
				<td><%= order.user.phone_number %></td>
				<td class="text-center"><%= order.qty %></td>
				<td><%= order.pickup_location %></td>
				<td><%= Order.payments[order.payment_type.to_s] %></td>
				<td class="text-center">$<%= order.cost %></td>
				<td><%= check_box_tag :filled, order.id, order.filled, class: 'filled' %></td>
				<td><%= check_box_tag :delivered, order.id, order.delivered, class: 'delivered' %></td>
			</tr>
		<% end %>
	</tbody>
</table>


<script>
	$('.filled').click(function(){
		$.ajax({
		  type: 'PATCH',
		  url: '/order/filled',
		  data: {checked: $(this).prop('checked'), id: $(this).val()},
		  dataType: 'json',
		  success: function(data){
		  	$(this).prop('disabled', true);
		  }
		})
	});

	$('.delivered').click(function(){
		$.ajax({
		  type: 'PATCH',
		  url: '/order/delivered',
		  data: {checked: $(this).prop('checked'), id: $(this).val()},
		  dataType: 'json',
		  success: function(data){
		  	$(this).prop('disabled', true);
		  }
		})
	});
</script>

app/views/shared/_alert.html.erb
  <% unless notice.nil? %>
	 	<p class="notice alert alert-primary alert-dismissible fade show" role="alert" style="margin-bottom: 10px;">
	 		<%= notice %>
	 		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		  </button>		
	 	</p>
  <% end %>

  <% unless alert.nil? %>
    <p class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-bottom: 10px;">
    	<%= alert %>
    	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		  </button>
    </p>
  <% end %>

app/views/shared/_order_details.html.erb
<div class="card text-center">
  <div class="card-header bg-primary">
    <h4>Order Number: <%= @order.id %></h4>
  </div>
  <div class="card-body">
    <h5 class="card-title">Order Details:</h5>
		<p>Name: <%= @order.user.first_name %> <%= @order.user.last_name %></p>
  
		<p>Phone Number: <%= @order.user.phone_number %></p>

		<p>Order Date: <%= @order.created_at.strftime("%m/%d/%Y") %></p>

    <p class="text-muted">Payment Type: <%= @payment_type %></p>

    <p class="text-muted">Total Cost Due: $<%= @order.cost %></p>

    <p class="text-muted">Order pickup at: <%= @order.pickup_location %></p>

    <p>Estimated Fill Date: <%= @order.estimate_delivery_date.strftime("%m-%d-%Y") %> <div class="text-muted">** We will contact you when your order is filled to confirm pickup date **</div></p>

		<p><%= link_to "Print", "#", onclick: "window.print();", class: "btn btn-primary" %></p>
  </div>
  <div class="card-footer text-muted">
		<h5>Order qty: <%= @order.qty %> dozen</h5>
  </div>
</div>

app/views/shared/_total_count.html.erb
<p>Currently Available Dozen: <%= farm.total_eggs %></p>